[options]
addons_path = /home/jalis/Desktop/odoo-tuts/18.0/odoo-18.0/addons,/home/jalis/Desktop/odoo-tuts/18.0/odoo-18.0/odoo/addons,/home/jalis/Desktop/odoo-tuts/18.0/custom_modules
db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo
admin_passwd = $pbkdf2-sha512$600000$inEO4TwnhBDiPIcQ4rxXyg$jYHQF/r8FScFNagiP3ZmuEot8ktkDJwagDhTaRvgQMmBtXukitSOtCT5MgElc3zuTIfFZFh7ZnQROhqjTWPC5A
http_port = 8069
log_level = info

